[package]
name = "tapeos"
version = "0.1.0"
edition = "2021"

[dependencies]
bluer = { version = "0.17.3", features = ["full"] }
idgenerator = "2.0.0"
futures = "0.3.31"
tokio = { version = "1.39.0", features = ["full"] }
env_logger = "0.11.6"