pub const MYSQL: &str = "MySQL";
pub const MYSQL_DESCRIPTION: &str = "MySQL can store, organize, and manage data in structured tables. It allows users to create, read, update, and delete data using SQL queries. It supports data sorting, filtering, and searching, and can handle complex operations like joining multiple tables. MySQL ensures data integrity through constraints, transactions, and indexing. It can manage large datasets, support multiple users simultaneously, and provide secure access control. Additionally, it enables backups, replication, and scalability for growing applications.";
pub const MONGODB: &str = "MongoDB";
pub const MONGODB_DESCRIPTION: &str = "MongoDB is a NoSQL database that stores data in flexible, JSON-like documents instead of tables. It can handle unstructured or semi-structured data, making it ideal for dynamic or evolving data models. MongoDB allows you to store, query, and manage large volumes of data efficiently. It supports indexing for fast searches, horizontal scaling for handling big data, and replication for high availability. MongoDB also enables complex queries, aggregation, and real-time analytics, making it suitable for modern applications with diverse data needs.";
pub const GOOGLE_DRIVE: &str = "Google Drive";
pub const GOOGLE_DRIVE_DESCRIPTION: &str = "Google Drive is a cloud-based storage service that allows you to store, share, and access files from anywhere. It can store documents, photos, videos, and other file types, and sync them across devices. You can create and edit files using Google Workspace tools like Docs, Sheets, and Slides directly within Drive. It supports file sharing with customizable permissions, collaboration in real-time, and version history to track changes. Google Drive also provides search functionality to quickly find files and integrates with other Google services and third-party apps.";
const SMART_PHONE: &str = "Smartphone";
const SMART_PHONE_DESCRIPTION: &str = "Smartphone is a multifunctional portable device with functions such as navigation, transportation service scheduling, itinerary booking, and information recording. Users can use it to obtain real-time location information, plan routes, book transportation (such as flights, taxis, etc.), and record and manage personal schedules or memo information;";
const SMART_HOME_SYSTEM: &str = "Smart home system";
const SMART_HOME_SYSTEM_DESCRIPTION: &str = "Smart home system is an automated home management solution that can perform specific tasks based on user preset instructions or conditions. For example, it can assist users in organizing and packing pre-set items (such as luggage), and optimize the travel preparation process by linking with the user's other devices;";
const SELF_DRIVING_CAR: &str = "Self-driving car";
const SELF_DRIVING_CAR_DESCRIPTION: &str = "Self-driving car is a means of transportation with autonomous navigation capabilities. It can automatically plan routes and arrive at designated locations safely based on the destination information entered by the user. It is suitable for short or long-distance travel and can be seamlessly connected with other transportation services (such as flights);";

pub const INTENT_INPUT_DESCRIPTION: &str = "Intent Input is a device which can get intent from user, but can not reveive any intent from other ways";
